add_test( [==[SimulationConfig parses correctly from default JSON]==] /workspaces/CellEvoX/CellEvoX/build_skip_gui/bin/CellEvoXTests [==[SimulationConfig parses correctly from default JSON]==]  )
set_tests_properties( [==[SimulationConfig parses correctly from default JSON]==] PROPERTIES WORKING_DIRECTORY /workspaces/CellEvoX/CellEvoX/build_skip_gui)
add_test( [==[Cell Initialization and Inheritance]==] /workspaces/CellEvoX/CellEvoX/build_skip_gui/bin/CellEvoXTests [==[Cell Initialization and Inheritance]==]  )
set_tests_properties( [==[Cell Initialization and Inheritance]==] PROPERTIES WORKING_DIRECTORY /workspaces/CellEvoX/CellEvoX/build_skip_gui)
add_test( [==[SimulationEngine Core Processing]==] /workspaces/CellEvoX/CellEvoX/build_skip_gui/bin/CellEvoXTests [==[SimulationEngine Core Processing]==]  )
set_tests_properties( [==[SimulationEngine Core Processing]==] PROPERTIES WORKING_DIRECTORY /workspaces/CellEvoX/CellEvoX/build_skip_gui)
add_test( [==[Simulation: High-Performance Regression]==] /workspaces/CellEvoX/CellEvoX/build_skip_gui/bin/CellEvoXTests [==[Simulation: High-Performance Regression]==]  )
set_tests_properties( [==[Simulation: High-Performance Regression]==] PROPERTIES WORKING_DIRECTORY /workspaces/CellEvoX/CellEvoX/build_skip_gui)
set( CellEvoXTests_TESTS [==[SimulationConfig parses correctly from default JSON]==] [==[Cell Initialization and Inheritance]==] [==[SimulationEngine Core Processing]==] [==[Simulation: High-Performance Regression]==])
